from enum import Enum

class Implementation(Enum):
    # CHANGE TO LISTS
    OSC_1_AMP = 14
    OSC_2_AMP = 15
    OSC_3_AMP = 16
    OSC_4_AMP = 17
    OSC_5_AMP = 18
    HPF_CUTOFF = 19
    HPF_WET = 20
    LPF_CUTOFF = 21
    LPF_WET = 22
    ENV_ATTACK = 23
    ENV_DECAY = 24
    ENV_SUSTAIN = 25
    ENV_RELEASE = 26
    DELAY_TIME = 27
    DELAY_FEEDBACK = 28
    DELAY_WET = 29
    LFO_SHAPE = "LFO_SHAPE"
    LFO_PARAMETER = "LFO_PARAMETER"
    LFO_FREQUENCY = "LFO_FREQUENCY"
    LFO_AMOUNT = "LFO_AMOUNT"
    VEL_SENSITIVITY = "VEL_SENSITIVITY"